Feature/worms (#121)
ALGORITHMS
----------
* Fix neighborhood W
* Geometric worms born out of Seth's Undirected Worms.
* Can have Villain W>1 with smart updating schemes.


OBSERVABLES
-----------
* {Not,Only} observable attributes
* Improve frozen observable reporting.

Previously, if you called ensemble.autocorrelation_time it might raise

> ValueError: The fluctuations are too small to reliably determine an autocorrelation.

But you wouldn't know which observable was the problematic one.

> The above exception was the direct cause of the following exception:
> ...
> ValueError: InternalEnergyDensity does not fluctuate enough

assuming the InternalEnergyDensity is the problematic observable.

ANALYSIS
--------
* Pass dict of kwargs to monte carlo history plot
* comparison_plot submodule, docs, and example
* Catch NotImplementedError in ensemble.measure()

CODE
----
* Reorganize generators (#117)

If we can develop W≠1 Villain-formulation algorithms

    https://github.com/evanberkowitz/supervillain/issues/113
    https://github.com/evanberkowitz/supervillain/issues/112

it will behoove us to keep the generators a bit more organized.  Here I
have separated the generators into Villain and Worldline, which
parallels how the actions themselves are organized.

* H5able --> ReadWriteable
* .gitignore: .csv and .code-workspace files and workbooks directory for tests and practice files


DOCS
----
* Some equation referencing
* Prokof'ev and Svistunov PhysRevLett.87.160601, Alet and Sørensen PhysRevE.68.026702
* Rephrase the W≠1 hedging in the Villain docs
* Villain worm algorithm + docs
* Villain worm example
* example/worldline-algorithm-comparison
    Like the action comparison, but for the local {Plaquette+Wrapping}Update
    vs the worm
* Remove linenumbers from license snippet
* Plotting examples all call plt.show



---------

Co-authored-by: SethBuesing <112661629+SethBuesing@users.noreply.github.com>
Co-authored-by: Seth Buesing <coepsbuesing@gmail.com>