Improve frozen observable reporting.
Previously, if you called ensemble.autocorrelation_time it might raise

> ValueError: The fluctuations are too small to reliably determine an autocorrelation.

But you wouldn't know which observable was the problematic one.

> The above exception was the direct cause of the following exception:
> ...
> ValueError: InternalEnergyDensity does not fluctuate enough

assuming the InternalEnergyDensity is the problematic observable.