Feature/villain worm (#120)
ALGORITHMS
----------
* Fix neighborhood W

OBSERVABLES
-----------
* {Not,Only} observable attributes
* Improve frozen observable reporting.

Previously, if you called ensemble.autocorrelation_time it might raise

> ValueError: The fluctuations are too small to reliably determine an autocorrelation.

But you wouldn't know which observable was the problematic one.

> The above exception was the direct cause of the following exception:
> ...
> ValueError: InternalEnergyDensity does not fluctuate enough

assuming the InternalEnergyDensity is the problematic observable.

ANALYSIS
--------
* Pass dict of kwargs to monte carlo history plot
* comparison_plot submodule, docs, and example


DOCS
----
* Some equation referencing
* Prokof'ev and Svistunov PhysRevLett.87.160601, Alet and Sørensen PhysRevE.68.026702
* Rephrase the W≠1 hedging in the Villain docs
* Villain worm algorithm + docs
* Villain worm example


This may be better moved to the analysis submodule + documented more
thoroughly.